"""empty message

Revision ID: 78e6e1372dbe
Revises: None
Create Date: 2016-08-13 16:09:45.176071

"""

# revision identifiers, used by Alembic.
revision = '78e6e1372dbe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    ### end Alembic commands ###
